In [32]:
import pandas as pd
from scipy.stats import shapiro

In [33]:
def add_columns_per_m(df):
    df['stops_per_m'] = df['numOfStops'] / df['route_length']
    df['emission_per_m'] = df['emission'] / df['route_length']
    df['elevation_up_per_m'] = df['elevation_up'] / df['route_length']
    df['elevation_down_per_m'] = df['elevation_down'] / df['route_length']
    df['timeloss_per_m'] = df['timeloss'] / df['route_length']

    return df

In [34]:
def drop_unnecessary_columns(df):
    return df.drop(['routeId', 'tripId', 'loc', 'seed'], axis=1)

In [35]:
def drop_stops_and_route_length(df):
    return df.drop(['numOfStops', 'route_length'], axis=1)

In [36]:
def drop_redundant_columns(df):
    return df.drop(['numOfStops', 'route_length', 'emission', 'elevation_up', 'elevation_down', 'timeloss'], axis=1)

In [37]:
def add_delta_elevation(df):
    df['delta_elevation_per_m'] = df['elevation_up_per_m'] + df['elevation_down_per_m']
    return df.drop(['elevation_up_per_m', 'elevation_down_per_m'], axis=1)

In [38]:
tableEmission = pd.read_csv('C:\\Users\\Admin\\Desktop\\onlab\\bme_onlab\\data\\emissionData.csv', delimiter=';')
tableBattery = pd.read_csv('C:\\Users\\Admin\\Desktop\\onlab\\bme_onlab\\data\\batteryData.csv', delimiter=';')

## Drop unnecessary columns

In [39]:
#tableEmission = tableEmission[tableEmission['seed'] <= 1]
#tableBattery = tableBattery[tableBattery['seed'] <= 1]
#tableBattery

In [40]:
tableEmission = drop_unnecessary_columns(tableEmission)
tableEmission

,avgSpeed,timeloss,route_length,elevation_up,elevation_down,trafficScale,numOfStops,emission
0,4.563878,69.93,673.45,8.3200,-10.7300,0.3,2,267.681119
1,6.863021,26.94,660.10,2.4600,-2.3200,0.3,2,222.161497
2,5.729324,119.93,3647.97,105.7300,-68.5600,0.3,12,1140.608494
3,2.436582,1236.73,4048.13,22.4600,-79.7000,0.3,11,2167.769607
4,4.027150,574.89,3968.76,81.2400,-24.6800,0.3,11,1808.274473
...,...,...,...,...,...,...,...,...
1544,7.364698,114.16,3682.47,17.4205,-259.2299,1.0,10,2204.557394
1545,7.064659,287.21,7594.63,89.5601,-353.9124,1.0,21,3379.066551
1546,7.335325,103.34,3682.47,17.3795,-259.1875,1.0,10,2178.756388
1547,6.359938,287.59,5501.48,30.7344,-339.3016,1.0,15,3118.404556
1548,6.992434,112.51,3607.19,255.8022,-18.5987,1.0,10,2208.619399

In [41]:
tableBattery = drop_unnecessary_columns(tableBattery)
tableBattery

,avgSpeed,timeloss,route_length,elevation_up,elevation_down,trafficScale,numOfStops,emission
0,1.013591,339.81,575.27,5.3400,-7.9300,0.3,2,69.618208
1,6.425740,33.46,660.10,2.3400,-2.3200,0.3,2,141.947410
2,5.872307,134.66,3647.97,105.6900,-68.5300,0.3,12,1252.215855
3,3.558635,614.38,4075.61,22.7300,-79.8800,0.3,11,395.144354
4,2.757995,1019.37,4018.91,80.8600,-24.3000,0.3,11,953.118991
...,...,...,...,...,...,...,...,...
1488,7.164103,144.42,3682.47,17.2080,-259.0175,1.0,10,-217.477909
1489,6.941962,308.87,7594.63,90.1784,-354.5309,1.0,21,388.018400
1490,6.622927,158.25,3682.47,17.7751,-259.5846,1.0,10,-369.953155
1491,6.604280,195.49,5501.48,30.7932,-339.3615,1.0,15,-400.225001
1492,6.603968,171.11,3607.19,255.9831,-18.7796,1.0,10,2322.327216

## create new columns from existing ones

In [42]:
#tableBattery = add_route_length_per_stop(tableBattery)
#tableEmission = add_route_length_per_stop(tableEmission)
#tableEmission

In [43]:
tableBattery = add_columns_per_m(tableBattery)
tableEmission = add_columns_per_m(tableEmission)

In [44]:
tableBattery = drop_redundant_columns(tableBattery)
tableEmission = drop_redundant_columns(tableEmission)
tableBattery

,avgSpeed,trafficScale,stops_per_m,emission_per_m,elevation_up_per_m,elevation_down_per_m,timeloss_per_m
0,1.013591,0.3,0.003477,0.121018,0.009283,-0.013785,0.590697
1,6.425740,0.3,0.003030,0.215039,0.003545,-0.003515,0.050689
2,5.872307,0.3,0.003290,0.343264,0.028972,-0.018786,0.036914
3,3.558635,0.3,0.002699,0.096953,0.005577,-0.019600,0.150746
4,2.757995,0.3,0.002737,0.237159,0.020120,-0.006046,0.253643
...,...,...,...,...,...,...,...
1488,7.164103,1.0,0.002716,-0.059058,0.004673,-0.070338,0.039218
1489,6.941962,1.0,0.002765,0.051091,0.011874,-0.046682,0.040670
1490,6.622927,1.0,0.002716,-0.100463,0.004827,-0.070492,0.042974
1491,6.604280,1.0,0.002727,-0.072749,0.005597,-0.061685,0.035534
1492,6.603968,1.0,0.002772,0.643805,0.070965,-0.005206,0.047436

In [45]:
tableEmissionDeltaEle = add_delta_elevation(tableEmission)
tableBatteryDeltaEle = add_delta_elevation(tableBattery)

TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

In [ ]:
tableBattery.to_csv('battery.csv', index=False, sep=';')
tableEmission.to_csv('emission.csv', index=False, sep=';')
tableBatteryDeltaEle.to_csv('batteryDeltaEle.csv', index=False, sep=';')
tableEmissionDeltaEle.to_csv('emissionDeltaEle.csv', index=False, sep=';')

In [ ]:

# Assuming df is your DataFrame
for column in tableEmission.columns:
    stat, p = shapiro(tableEmission[column])
    print(f'Column: {column}, p-value: {p}')
    if p > 0.05:
        print(f'Column "{column}" appears to be normally distributed.')
    else:
        print(f'Column "{column}" does not appear to be normally distributed.')

Column: avgSpeed, p-value: 4.165921792611211e-14
Column "avgSpeed" does not appear to be normally distributed.
Column: trafficScale, p-value: 2.339583429787654e-34
Column "trafficScale" does not appear to be normally distributed.
Column: stops_per_m, p-value: 7.103441155736681e-41
Column "stops_per_m" does not appear to be normally distributed.
Column: emission_per_m, p-value: 7.075934781115093e-44
Column "emission_per_m" does not appear to be normally distributed.
Column: elevation_up_per_m, p-value: 3.546610540841399e-31
Column "elevation_up_per_m" does not appear to be normally distributed.
Column: elevation_down_per_m, p-value: 1.1121559675571608e-33
Column "elevation_down_per_m" does not appear to be normally distributed.
Column: timeloss_per_m, p-value: 1.8382144219785e-53
Column "timeloss_per_m" does not appear to be normally distributed.